name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # adjust if a specific minor version is needed

    - name: Install dependencies
      run: |
        cd Flask
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure App Service
      run: |
        cd Flask
        az webapp up --name cinesageinsights --resource-group DefaultResourceGroup-eastus2 --sku F1
